// <auto-generated />
namespace University_Management.Migrations.Project_DbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InsertingsemesterdatatoColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertingsemesterdatatoColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130542137_InsertingsemesterdatatoColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
